name: C++ Build with Bear

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout your code from the repository

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential  # Install essential build tools
          sudo apt-get install -y libsdl2-dev libsdl2-image-dev  # Install SDL2 dependencies
          sudo apt-get install -y bear  # Install Bear (Build EAR) to generate compile_commands.json
          bear --version  # Check if bear was installed correctly

      - name: Generate compilation database with Bear
        run: |
          bear -- make  # Use Bear to wrap the make command and generate compile_commands.json
          
      - name: Build with make
        run: |
          make  # Run make to build your project (this is also wrapped by bear)

      - name: Run tests (optional)
        run: |
          ./bin/main  # Run the compiled executable (optional step)

      - name: Print file structure
        run: |
          ls -R  # List all files to verify the file structure (e.g., to see if Makefile exists)
